### ISSUE TITLE
Saphir - unbounded recourse problem

### ISSUE THREAD

**Issue by juantorres91** [vitaut/splib#2]
Hi,

I'm benchmarking several approaches to solve 2-stage SLP problems, i found very useful your repository becouse it compiles most of the availiable problems in the SMPS format. However, I'm having some problems evaluating the SAPHIR cases, there is some infeasibility in the formulation (unbounded recourse function).  I'm testing the problems in Fortsp and Pyomo (i build my own parser). From my observation the issue is located in the bounds section, related to the definition of several of the free variables (FR).

I understand those instances were originally created from SAMPL and derived from the SAPHIR model, which i haven't been able to find. I would like to ask you if you can correct the problem or guide me on how to find the model and data to build and correct the SMPS files.

Thank you in advance,

Juan José

**Comment by vitaut** [comment]
I don't have the original models. You could try contacting their authors:

> König, D., Suhl, L., Koberstein, A.: Optimierung des Gasbezugs im liberalisierten Gasmarkt unter
Berücksichtigung von Röhren- und Untertagespeichern. In: Sammelband zur VDI Tagung “Optimierung in der Energiewirtschaft” in Leverkusen (2007)
